author: K0Gs
database: false
main: statue.mod_statue
name: statue
startup: postworld
version: '1.2'
softdepend: [CoreProtect,WorldGuard,PlotMe]
depends: [Vault]
commands:
   statue:
      permission: statue.build
      description: Build a statue or two, of me or of you.
      usage: /statue <player> <hat>  /statue pixel <player_Name>  /statue head <player_Name>
permissions:
   statue.build:
      description: Gives access to all statue commands
      default: op
